# Generated by Django 4.0.2 on 2022-03-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='messagge',
            field=models.TextField(blank=True),
        ),
    ]
